from .description import constrained_quadratic_problem_description,\
    unconstrained_quadratic_problem_description
from .plant_constrained import constrained_quadratic_problem_plant
from .plant_unconstrained import unconstrained_quadratic_problem_plant